---
username: vagrant

password: vagrant

shell: /bin/bash

ssh_port: 22

packages:
  - vim
  - tmux
  - htop
  - neofetch
  - speedtest-cli

lan_subnet: 192.168.1.0/24

lan_base: "{{ lan_subnet | regex_replace('.0/[0-9]{2}', '') }}"

homeserver_ip: "{{ lan_base }}.230"